### ISSUE TITLE
Executing the sample code leads to AttributeError: 'NavigableString' object has no attribute 'contents'

### ISSUE THREAD

**Issue by kloklojul** [Jaymon/wishlist#23]
installing this via pip and than running the sample code provided leads to this error: 
AttributeError: 'NavigableString' object has no attribute 'contents'

Traceback (most recent call last):
  File "woshlost.py", line 9, in <module>
    print(item.jsonable())
  File "\wishlist\core.py", line 399, in jsonable
    json_item["author"] = self.author
  File "\wishlist\core.py", line 233, in author
    if author is None or len(author.contents) < 1:
  File "\bs4\element.py", line 963, in __getattr__
    raise AttributeError(
AttributeError: 'NavigableString' object has no attribute 'contents'

**Comment by Jaymon** [comment]
I'm pretty sure this is fixed in [v0.5.4](https://github.com/Jaymon/wishlist/commit/699d2662f249a03a31f3a28d970b66151552d428#diff-3513add50f0d134db4aae1dd0163d5d21eff9447ef210cf62cf22f9178a1f940R58) which I was running personally to make sure no other bugs popped up before pushing it out to pypi.  You can install the latest directly from github:

```
pip install --upgrade "git+https://github.com/Jaymon/wishlist#egg=wishlist"
```

Sorry for the long delay, I'm not sure why Github has stopped notifying me of issues in a way that I would actually notice them
